spring:
  application:
    name: spring-cloud-gateway-demo
  cloud:
    gateway:
      routes:
      - id: service1
        uri: http://localhost:8081
        predicates:
          - Path=/service1/**
        filters:
          - RewritePath=/service1, /
      - id: service2
        uri: http://localhost:8082
        predicates:
          - Path=/service2/**
        filters:
          - RewritePath=/service2, /
      - id: service3
        uri: http://localhost:8083
        predicates:
          - Path=/service3/**
        filters:
          - RewritePath=/service3, /


